def options(ctx):
  pass
    
def configure(ctx):
  pass

def build(bld):
  bld.shlib(
       source       = 'PrefixSum.cpp PrefixSumNode.cpp PrefixSumLeaf.cpp',
       target       = 'prefixsum',
       name         = 'PREFIXSUM',
       includes     = '.')
  bld.program(
       features     = 'gtest',
       source       = 'PrefixSumLeafTest.cpp',
       target       = 'prefixsumleaftest',
       use          = 'PREFIXSUM',
       includes     = '.')
  bld.program(
       features     = 'gtest',
       source       = 'PrefixSumTest.cpp',
       target       = 'prefixsumtest',
       use          = 'PREFIXSUM',
       includes     = '.')
  bld.install_files('${PREFIX}/include/prefixsum', bld.path.ant_glob('*.hpp'))
