def options(ctx):
  pass
    
def configure(ctx):
  pass

def build(bld):
  bld.program(
       source       = 'PerformanceTest.cpp',
       target       = 'PerformanceTest',
       use          = 'PREFIXSUM',
       includes     = '.')
